config/routes.rb
Rails.application.routes.draw do
  resources :multiplechoices

  resources :questions

  resources :users

  root 'users#index'

end

app/models/multiplechoice.rb
class Multiplechoice < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_one    :multiplechoice
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/multiplechoices_controller.rb
class MultiplechoicesController < ApplicationController
  before_action :set_multiplechoice, only: [:show, :edit, :update, :destroy]

  # GET /multiplechoices
  # GET /multiplechoices.json
  def index
    @multiplechoices = Multiplechoice.all
  end

  # GET /multiplechoices/1
  # GET /multiplechoices/1.json
  def show
  end

  # GET /multiplechoices/new
  def new
    @multiplechoice = Multiplechoice.new
  end

  # GET /multiplechoices/1/edit
  def edit
  end

  # POST /multiplechoices
  # POST /multiplechoices.json
  def create
    @multiplechoice = Multiplechoice.new(multiplechoice_params)

    respond_to do |format|
      if @multiplechoice.save
        format.html { redirect_to @multiplechoice, notice: 'Multiplechoice was successfully created.' }
        format.json { render :show, status: :created, location: @multiplechoice }
      else
        format.html { render :new }
        format.json { render json: @multiplechoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /multiplechoices/1
  # PATCH/PUT /multiplechoices/1.json
  def update
    respond_to do |format|
      if @multiplechoice.update(multiplechoice_params)
        format.html { redirect_to @multiplechoice, notice: 'Multiplechoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @multiplechoice }
      else
        format.html { render :edit }
        format.json { render json: @multiplechoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /multiplechoices/1
  # DELETE /multiplechoices/1.json
  def destroy
    @multiplechoice.destroy
    respond_to do |format|
      format.html { redirect_to multiplechoices_url, notice: 'Multiplechoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_multiplechoice
      @multiplechoice = Multiplechoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def multiplechoice_params
      params.require(:multiplechoice).permit(:choice1, :choice2, :choice3, :choice4)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :emailid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/multiplechoices_helper.rb
module MultiplechoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/multiplechoices/_form.html.erb
<%= form_for(@multiplechoice) do |f| %>
  <% if @multiplechoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@multiplechoice.errors.count, "error") %> prohibited this multiplechoice from being saved:</h2>

      <ul>
      <% @multiplechoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :choice1 %><br>
    <%= f.text_area :choice1 %>
  </div>
  <div class="field">
    <%= f.label :choice2 %><br>
    <%= f.text_area :choice2 %>
  </div>
  <div class="field">
    <%= f.label :choice3 %><br>
    <%= f.text_area :choice3 %>
  </div>
  <div class="field">
    <%= f.label :choice4 %><br>
    <%= f.text_area :choice4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/multiplechoices/edit.html.erb
<h1>Editing multiplechoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @multiplechoice %> |
<%= link_to 'Back', multiplechoices_path %>

app/views/multiplechoices/index.html.erb
<h1>Listing multiplechoices</h1>

<table>
  <thead>
    <tr>
      <th>Choice1</th>
      <th>Choice2</th>
      <th>Choice3</th>
      <th>Choice4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @multiplechoices.each do |multiplechoice| %>
      <tr>
        <td><%= multiplechoice.choice1 %></td>
        <td><%= multiplechoice.choice2 %></td>
        <td><%= multiplechoice.choice3 %></td>
        <td><%= multiplechoice.choice4 %></td>
        <td><%= link_to 'Show', multiplechoice %></td>
        <td><%= link_to 'Edit', edit_multiplechoice_path(multiplechoice) %></td>
        <td><%= link_to 'Destroy', multiplechoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Multiplechoice', new_multiplechoice_path %>

app/views/multiplechoices/new.html.erb
<h1>New multiplechoice</h1>

<%= render 'form' %>

<%= link_to 'Back', multiplechoices_path %>

app/views/multiplechoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Choice1:</strong>
  <%= @multiplechoice.choice1 %>
</p>

<p>
  <strong>Choice2:</strong>
  <%= @multiplechoice.choice2 %>
</p>

<p>
  <strong>Choice3:</strong>
  <%= @multiplechoice.choice3 %>
</p>

<p>
  <strong>Choice4:</strong>
  <%= @multiplechoice.choice4 %>
</p>

<%= link_to 'Edit', edit_multiplechoice_path(@multiplechoice) %> |
<%= link_to 'Back', multiplechoices_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Question:</strong>
  <%= @question.question %>
</h3>
<p>Choices for the question </p>
<ul>
  <br><%= check_box_tag :@question,1%><%= @question.multiplechoice.choice1%>&nbsp<%= check_box_tag :@question,2%><%= @question.multiplechoice.choice2%></br>
  <br><%= check_box_tag :@question,3%><%= @question.multiplechoice.choice3%>&nbsp<%= check_box_tag :@question,4%><%= @question.multiplechoice.choice4%></br> 
</ul>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :emailid %><br>
    <%= f.text_area :emailid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Emailid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.emailid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Emailid:</strong>
  <%= @user.emailid %>
</p>


<h3>Question for this User</h3>

<ul>
  <%- @user.questions.each do |question| %>
  <li><%=link_to question.question, question %></li>
  <%- end %>
</ul>




<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>